<?php /* Smarty version 2.6.10, created on 2014-10-31 20:29:06
         compiled from Welcome.tpl */

$this->_cache_serials['Lib/App/../../_Cache/Smarty\%%09^099^0997F726%%Welcome.tpl.inc'] = 'd0d539bf9784d880985ddea0622dcd2e';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'webcontrol', 'Welcome.tpl', 6, false),array('function', 'url', 'Welcome.tpl', 184, false),)), $this); ?>
<?php
function _smarty_tplfunc_d0d539bf9784d880985ddea0622dcd2e_0(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/ext/resources/css/ext-all.css"), $_smarty);
}


function _smarty_tplfunc_d0d539bf9784d880985ddea0622dcd2e_1(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/ext/adapter/ext/ext-base.js"), $_smarty);
}


function _smarty_tplfunc_d0d539bf9784d880985ddea0622dcd2e_2(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/ext/ext-all.js"), $_smarty);
}


function _smarty_tplfunc_d0d539bf9784d880985ddea0622dcd2e_3(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/ext/ux/Portal.js"), $_smarty);
}


function _smarty_tplfunc_d0d539bf9784d880985ddea0622dcd2e_4(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/ext/ux/PortalColumn.js"), $_smarty);
}


function _smarty_tplfunc_d0d539bf9784d880985ddea0622dcd2e_5(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/ext/ux/Portlet.js"), $_smarty);
}


function _smarty_tplfunc_d0d539bf9784d880985ddea0622dcd2e_6(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/ext/ux/css/Portal.css"), $_smarty);
}


function _smarty_tplfunc_d0d539bf9784d880985ddea0622dcd2e_7(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/jquery.js"), $_smarty);
}


function _smarty_tplfunc_d0d539bf9784d880985ddea0622dcd2e_8(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/Common.js"), $_smarty);
}


function _smarty_tplfunc_d0d539bf9784d880985ddea0622dcd2e_9(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => 'Trade_Order','action' => 'Trace'), $_smarty);
}



?>
