<?php /* Smarty version 2.6.10, created on 2014-10-30 14:26:30
         compiled from Search/kuweiId.tpl */

$this->_cache_serials['Lib/App/../../_Cache/Smarty\%%24^245^245B85CE%%kuweiId.tpl.inc'] = 'ea439aa017a3972e75ef2ae4477ab70e';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'webcontrol', 'Search/kuweiId.tpl', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_ea439aa017a3972e75ef2ae4477ab70e_0(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'Tmisoptions','model' => 'jichu_kuwei','selected' => $_smarty->_tpl_vars['arr_condition']['kuweiId'],'emptyText' => '选择仓库'), $_smarty);
}



?>
