<?php /* Smarty version 2.6.10, created on 2014-10-30 13:50:57
         compiled from Trade/ColorAuutoCompleteJs.tpl */

$this->_cache_serials['Lib/App/../../_Cache/Smarty\%%28^287^287C7CA2%%ColorAuutoCompleteJs.tpl.inc'] = '2b9945f2aa4a98adeb2c696357144e3d';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'webcontrol', 'Trade/ColorAuutoCompleteJs.tpl', 1, false),)), $this); ?>
<?php
function _smarty_tplfunc_2b9945f2aa4a98adeb2c696357144e3d_0(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/bootstrap/bootstrap3.0.3/js/bootstrap.window.js"), $_smarty);
}



?>
