<?php /* Smarty version 2.6.10, created on 2014-11-08 12:54:24
         compiled from Jichu/FeiyongEdit.tpl */

$this->_cache_serials['Lib/App/../../_Cache/Smarty\%%33^331^331DB647%%FeiyongEdit.tpl.inc'] = 'c1e8cf5ae6d6d7cde9f29555388b26a5';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'url', 'Jichu/FeiyongEdit.tpl', 22, false),)), $this); ?>
<?php
function _smarty_tplfunc_c1e8cf5ae6d6d7cde9f29555388b26a5_0(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => $_GET['controller'],'action' => 'save'), $_smarty);
}


function _smarty_tplfunc_c1e8cf5ae6d6d7cde9f29555388b26a5_1(&$_smarty)
{
echo $_smarty->_plugins['function']['url'][0][0]->_pi_func_url(array('controller' => $_GET['controller']), $_smarty);
}



?>
