<?php /* Smarty version 2.6.10, created on 2014-11-15 15:52:08
         compiled from Caiwu/Yf/viewTpl.tpl */

$this->_cache_serials['Lib/App/../../_Cache/Smarty\%%35^35C^35C8152E%%viewTpl.tpl.inc'] = 'cc109056a4a18bd246e7969a780ab09a';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'webcontrol', 'Caiwu/Yf/viewTpl.tpl', 7, false),)), $this); ?>
<?php
function _smarty_tplfunc_cc109056a4a18bd246e7969a780ab09a_0(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/jquery.js"), $_smarty);
}


function _smarty_tplfunc_cc109056a4a18bd246e7969a780ab09a_1(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/jquery.validate.js"), $_smarty);
}


function _smarty_tplfunc_cc109056a4a18bd246e7969a780ab09a_2(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/Calendar/WdatePicker.js"), $_smarty);
}


function _smarty_tplfunc_cc109056a4a18bd246e7969a780ab09a_3(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/common.js"), $_smarty);
}


function _smarty_tplfunc_cc109056a4a18bd246e7969a780ab09a_4(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Css/EditCommon.css"), $_smarty);
}


function _smarty_tplfunc_cc109056a4a18bd246e7969a780ab09a_5(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Css/validate.css"), $_smarty);
}


function _smarty_tplfunc_cc109056a4a18bd246e7969a780ab09a_6(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/ymPrompt/ymPrompt.js"), $_smarty);
}


function _smarty_tplfunc_cc109056a4a18bd246e7969a780ab09a_7(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/ymPrompt/skin/bluebar/ymPrompt.css"), $_smarty);
}


function _smarty_tplfunc_cc109056a4a18bd246e7969a780ab09a_8(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/TmisPopup.js"), $_smarty);
}



?>
