<?php /* Smarty version 2.6.10, created on 2015-09-12 09:34:01
         compiled from Acm/ShowFunc.tpl */

$this->_cache_serials['Lib/App/../../_Cache/Smarty\%%40^40F^40FB7723%%ShowFunc.tpl.inc'] = '74a76b2e84edfa68db05f73d12d2f691';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'webcontrol', 'Acm/ShowFunc.tpl', 4, false),)), $this); ?>
<?php
function _smarty_tplfunc_74a76b2e84edfa68db05f73d12d2f691_0(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/jquery.js"), $_smarty);
}



?>
