<?php /* Smarty version 2.6.10, created on 2014-10-30 13:50:56
         compiled from Main2Son/text.tpl */

$this->_cache_serials['Lib/App/../../_Cache/Smarty\%%7D^7D2^7D271130%%text.tpl.inc'] = '9b2b139d76e224c072ba29f699990c2e';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'default', 'Main2Son/text.tpl', 3, false),array('function', 'webcontrol', 'Main2Son/text.tpl', 5, false),)), $this); ?>
<?php
function _smarty_tplfunc_9b2b139d76e224c072ba29f699990c2e_0(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'bttext','itemName' => ((is_array($_tmp=@$_smarty->_tpl_vars['item']['name'])) ? $_smarty->_run_mod_handler('default', true, $_tmp, @$_smarty->_tpl_vars['key']) : smarty_modifier_default($_tmp, @$_smarty->_tpl_vars['key'])),'value' => $_smarty->_tpl_vars['item']['value'],'disabled' => $_smarty->_tpl_vars['item']['disabled'],'readonly' => $_smarty->_tpl_vars['item']['readonly'],'addonPre' => $_smarty->_tpl_vars['item']['addonPre'],'addonEnd' => $_smarty->_tpl_vars['item']['addonEnd']), $_smarty);
}



?>
