<?php /* Smarty version 2.6.10, created on 2016-03-07 11:15:07
         compiled from Trade/sonTpl.tpl */

$this->_cache_serials['Lib/App/../../_Cache/Smarty\%%87^879^8795CE5F%%sonTpl.tpl.inc'] = '2902f09ed41a68deedc1c25b8133b364';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'webcontrol', 'Trade/sonTpl.tpl', 1, false),)), $this); ?>
<?php
function _smarty_tplfunc_2902f09ed41a68deedc1c25b8133b364_0(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/bootstrap/bootstrap3.0.3/css/bootstrap.css"), $_smarty);
}



?>
