<?php /* Smarty version 2.6.10, created on 2014-10-30 13:50:56
         compiled from Trade/otherInfoTpl.tpl */

$this->_cache_serials['Lib/App/../../_Cache/Smarty\%%9B^9BC^9BC03935%%otherInfoTpl.tpl.inc'] = '38c9a64310ec90fda6192e69386e7b26';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'webcontrol', 'Trade/otherInfoTpl.tpl', 12, false),array('modifier', 'cat', 'Trade/otherInfoTpl.tpl', 44, false),)), $this); ?>
<?php
function _smarty_tplfunc_38c9a64310ec90fda6192e69386e7b26_0(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'btBtnAdd'), $_smarty);
}


function _smarty_tplfunc_38c9a64310ec90fda6192e69386e7b26_1(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => $_smarty->_tpl_vars['item']['type'],'value' => $_smarty->_tpl_vars['item1'][$_smarty->_tpl_vars['key']]['value'],'kind' => $_smarty->_tpl_vars['item']['kind'],'itemName' => $_smarty->_tpl_vars['item']['name'],'readonly' => $_smarty->_tpl_vars['item']['readonly'],'disabled' => $_smarty->_tpl_vars['item']['disabled'],'width' => $_smarty->_tpl_vars['item']['width'],'options' => $_smarty->_tpl_vars['item']['options']), $_smarty);
}


function _smarty_tplfunc_38c9a64310ec90fda6192e69386e7b26_2(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => $_smarty->_tpl_vars['item']['type'],'value' => $_smarty->_tpl_vars['item1'][$_smarty->_tpl_vars['key']]['value'],'itemName' => $_smarty->_tpl_vars['item']['name'],'readonly' => $_smarty->_tpl_vars['item']['readonly'],'disabled' => $_smarty->_tpl_vars['item']['disabled']), $_smarty);
}



?>
