<?php /* Smarty version 2.6.10, created on 2014-11-03 09:39:43
         compiled from Main/text.tpl */

$this->_cache_serials['Lib/App/../../_Cache/Smarty\%%9D^9D4^9D443FB3%%text.tpl.inc'] = '9a59674d0705f63e8dd09ccfbeab3389';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'default', 'Main/text.tpl', 2, false),array('function', 'webcontrol', 'Main/text.tpl', 4, false),)), $this); ?>
<?php
function _smarty_tplfunc_9a59674d0705f63e8dd09ccfbeab3389_0(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'bttext','itemName' => ((is_array($_tmp=@$_smarty->_tpl_vars['item']['name'])) ? $_smarty->_run_mod_handler('default', true, $_tmp, @$_smarty->_tpl_vars['key']) : smarty_modifier_default($_tmp, @$_smarty->_tpl_vars['key'])),'value' => $_smarty->_tpl_vars['item']['value'],'disabled' => $_smarty->_tpl_vars['item']['disabled'],'readonly' => $_smarty->_tpl_vars['item']['readonly'],'addonPre' => $_smarty->_tpl_vars['item']['addonPre'],'addonEnd' => $_smarty->_tpl_vars['item']['addonEnd']), $_smarty);
}



?>
