<?php /* Smarty version 2.6.10, created on 2014-11-04 09:50:39
         compiled from Shengchan/Cangku/MadanRkJs.tpl */

$this->_cache_serials['Lib/App/../../_Cache/Smarty\%%C4^C41^C41CD8CC%%MadanRkJs.tpl.inc'] = '20cc63e9fdf7272de653c294698e3172';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'webcontrol', 'Shengchan/Cangku/MadanRkJs.tpl', 1, false),)), $this); ?>
<?php
function _smarty_tplfunc_20cc63e9fdf7272de653c294698e3172_0(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/jquery.json.js"), $_smarty);
}



?>
