<?php /* Smarty version 2.6.10, created on 2014-11-15 14:08:00
         compiled from Main2Son/_jsCommon.tpl */

$this->_cache_serials['Lib/App/../../_Cache/Smarty\%%D3^D3B^D3B46A51%%_jsCommon.tpl.inc'] = '9a905c2e03cb4aa08a77d942b0ee9374';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'webcontrol', 'Main2Son/_jsCommon.tpl', 2, false),array('modifier', 'default', 'Main2Son/_jsCommon.tpl', 12, false),array('modifier', 'json_encode', 'Main2Son/_jsCommon.tpl', 14, false),)), $this); ?>
<?php
function _smarty_tplfunc_9a905c2e03cb4aa08a77d942b0ee9374_0(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/Calendar/WdatePicker.js"), $_smarty);
}


function _smarty_tplfunc_9a905c2e03cb4aa08a77d942b0ee9374_1(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/common.js"), $_smarty);
}


function _smarty_tplfunc_9a905c2e03cb4aa08a77d942b0ee9374_2(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/bootstrap/bootstrap3.0.3/js/jquery.min.js"), $_smarty);
}


function _smarty_tplfunc_9a905c2e03cb4aa08a77d942b0ee9374_3(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/jquery.validate.js"), $_smarty);
}


function _smarty_tplfunc_9a905c2e03cb4aa08a77d942b0ee9374_4(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/bootstrap/bootstrap3.0.3/js/bootstrap.js"), $_smarty);
}


function _smarty_tplfunc_9a905c2e03cb4aa08a77d942b0ee9374_5(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/bootstrap/bootstrap3.0.3/js/tooltip.js"), $_smarty);
}


function _smarty_tplfunc_9a905c2e03cb4aa08a77d942b0ee9374_6(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/bootstrap/bootstrap3.0.3/js/jeffCombobox.js"), $_smarty);
}


function _smarty_tplfunc_9a905c2e03cb4aa08a77d942b0ee9374_7(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/bootstrap/bootstrap3.0.3/js/TableHeader.js"), $_smarty);
}



?>
