<?php /* Smarty version 2.6.10, created on 2014-10-28 13:13:06
         compiled from Search/huaxing.tpl */

$this->_cache_serials['Lib/App/../../_Cache/Smarty\%%D8^D8D^D8D4B390%%huaxing.tpl.inc'] = '924ae8736a0590eb6558983ef29822bc';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'webcontrol', 'Search/huaxing.tpl', 1, false),)), $this); ?>
<?php
function _smarty_tplfunc_924ae8736a0590eb6558983ef29822bc_0(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'Sysparam','item' => 'manuCodeName'), $_smarty);
}


function _smarty_tplfunc_924ae8736a0590eb6558983ef29822bc_1(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'Sysparam','item' => 'manuCodeName'), $_smarty);
}



?>
