<?php /* Smarty version 2.6.10, created on 2014-11-11 16:24:25
         compiled from Caiwu/Yf/Guozhang1.tpl */

$this->_cache_serials['Lib/App/../../_Cache/Smarty\%%E6^E6B^E6BCCC08%%Guozhang1.tpl.inc'] = 'f622a67e669af4a36181df2c7631c72b';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'webcontrol', 'Caiwu/Yf/Guozhang1.tpl', 7, false),)), $this); ?>
<?php
function _smarty_tplfunc_f622a67e669af4a36181df2c7631c72b_0(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/jquery.js"), $_smarty);
}


function _smarty_tplfunc_f622a67e669af4a36181df2c7631c72b_1(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/jquery.validate.js"), $_smarty);
}


function _smarty_tplfunc_f622a67e669af4a36181df2c7631c72b_2(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/Calendar/WdatePicker.js"), $_smarty);
}


function _smarty_tplfunc_f622a67e669af4a36181df2c7631c72b_3(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/common.js"), $_smarty);
}


function _smarty_tplfunc_f622a67e669af4a36181df2c7631c72b_4(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Css/EditCommon.css"), $_smarty);
}


function _smarty_tplfunc_f622a67e669af4a36181df2c7631c72b_5(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Css/validate.css"), $_smarty);
}


function _smarty_tplfunc_f622a67e669af4a36181df2c7631c72b_6(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/ymPrompt/ymPrompt.js"), $_smarty);
}


function _smarty_tplfunc_f622a67e669af4a36181df2c7631c72b_7(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/ymPrompt/skin/bluebar/ymPrompt.css"), $_smarty);
}


function _smarty_tplfunc_f622a67e669af4a36181df2c7631c72b_8(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/TmisPopup.js"), $_smarty);
}



?>
