<?php /* Smarty version 2.6.10, created on 2014-10-28 13:12:50
         compiled from Login.tpl */

$this->_cache_serials['Lib/App/../../_Cache/Smarty\%%E8^E8A^E8A2FF7B%%Login.tpl.inc'] = '6a5756a491fc44600f389cce24c60c9f';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'webcontrol', 'Login.tpl', 5, false),)), $this); ?>
<?php
function _smarty_tplfunc_6a5756a491fc44600f389cce24c60c9f_0(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'GetAppInf','varName' => 'systemName'), $_smarty);
}


function _smarty_tplfunc_6a5756a491fc44600f389cce24c60c9f_1(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/jquery.js"), $_smarty);
}



?>
