<?php /* Smarty version 2.6.10, created on 2014-10-30 15:06:22
         compiled from Tool/Dbchange/Edit.tpl */

$this->_cache_serials['Lib/App/../../_Cache/Smarty\%%F3^F3E^F3EEA3D2%%Edit.tpl.inc'] = 'd34a35721d58d516e4c729da43f2ad82';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'webcontrol', 'Tool/Dbchange/Edit.tpl', 5, false),array('modifier', 'date_format', 'Tool/Dbchange/Edit.tpl', 199, false),)), $this); ?>
<?php
function _smarty_tplfunc_d34a35721d58d516e4c729da43f2ad82_0(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/jquery.js"), $_smarty);
}


function _smarty_tplfunc_d34a35721d58d516e4c729da43f2ad82_1(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/Calendar/WdatePicker.js"), $_smarty);
}


function _smarty_tplfunc_d34a35721d58d516e4c729da43f2ad82_2(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/Common.js"), $_smarty);
}



?>
