<?php /* Smarty version 2.6.10, created on 2016-03-07 11:15:07
         compiled from Trade/TradeTracing.tpl */

$this->_cache_serials['Lib/App/../../_Cache/Smarty\%%F5^F53^F53FA76B%%TradeTracing.tpl.inc'] = 'e320bb915e1cb2c269bd3fa312db4a5c';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'webcontrol', 'Trade/TradeTracing.tpl', 6, false),array('modifier', 'json_encode', 'Trade/TradeTracing.tpl', 24, false),)), $this); ?>
<?php
function _smarty_tplfunc_e320bb915e1cb2c269bd3fa312db4a5c_0(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/ext/adapter/ext/ext-base.js"), $_smarty);
}


function _smarty_tplfunc_e320bb915e1cb2c269bd3fa312db4a5c_1(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/ext/ext-all.js"), $_smarty);
}


function _smarty_tplfunc_e320bb915e1cb2c269bd3fa312db4a5c_2(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/jquery.js"), $_smarty);
}


function _smarty_tplfunc_e320bb915e1cb2c269bd3fa312db4a5c_3(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/common.js"), $_smarty);
}


function _smarty_tplfunc_e320bb915e1cb2c269bd3fa312db4a5c_4(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Css/SearchItemTpl.css"), $_smarty);
}


function _smarty_tplfunc_e320bb915e1cb2c269bd3fa312db4a5c_5(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/ext/resources/css/ext-all.css"), $_smarty);
}


function _smarty_tplfunc_e320bb915e1cb2c269bd3fa312db4a5c_6(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Script/tblList.js"), $_smarty);
}


function _smarty_tplfunc_e320bb915e1cb2c269bd3fa312db4a5c_7(&$_smarty)
{
echo $_smarty->_plugins['function']['webcontrol'][0][0]->_pi_func_webcontrol(array('type' => 'LoadJsCss','src' => "Resource/Css/TblList.css"), $_smarty);
}



?>
